"use client";

import { useState } from 'react';
import { FileDown, Loader2 } from 'lucide-react';

interface Props {
  name: string;
  certId: string;
  issueDate: string;
}

export default function DownloadVerificationReport({ name, certId, issueDate }: Props) {
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    setLoading(true);
    try {
      const { jsPDF } = await import('jspdf');
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "in",
        format: "letter",
      });

      // Standard HR-Friendly Fonts
      pdf.setFont("helvetica", "bold");
      
      // Header
      pdf.setFontSize(24);
      pdf.setTextColor(15, 23, 42); // slate-900
      pdf.text("Credential Verification Report", 1, 1.5);
      
      pdf.setFontSize(10);
      pdf.setTextColor(100, 116, 139); // slate-500
      pdf.text("PLAYWRIGHT AUTOMATION ACADEMY", 1, 1.75);
      pdf.text("AUTOMATION EXCELLENCE INSTITUTE", 1, 1.9);

      // Divider
      pdf.setDrawColor(203, 213, 225); // slate-300
      pdf.line(1, 2.2, 7.5, 2.2);

      // Candidate Section
      pdf.setFontSize(14);
      pdf.setTextColor(15, 23, 42);
      pdf.text("Candidate Details", 1, 2.8);
      
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(71, 85, 105);
      pdf.text(`Name:`, 1, 3.2);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(15, 23, 42);
      pdf.text(name, 2.5, 3.2);

      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(71, 85, 105);
      pdf.text(`Credential:`, 1, 3.5);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(15, 23, 42);
      pdf.text("Automation Legend", 2.5, 3.5);

      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(71, 85, 105);
      pdf.text(`Certificate No:`, 1, 3.8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(15, 23, 42);
      pdf.text(certId, 2.5, 3.8);

      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(71, 85, 105);
      pdf.text(`Issue Date:`, 1, 4.1);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(15, 23, 42);
      pdf.text(issueDate, 2.5, 4.1);

      // Status
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(71, 85, 105);
      pdf.text(`Status:`, 1, 4.4);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(22, 163, 74); // green-600
      pdf.text("Verified / Active", 2.5, 4.4);

      // Divider
      pdf.setDrawColor(203, 213, 225);
      pdf.line(1, 4.8, 7.5, 4.8);

      // System Log
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(148, 163, 184); // slate-400
      const timestamp = new Date().toUTCString();
      pdf.text(`Report generated by ASA Cryptographic Verification System`, 1, 5.2);
      pdf.text(`Timestamp: ${timestamp}`, 1, 5.4);
      pdf.text(`Verification URL: https://academy.aegisautomation.com/credential/${certId}`, 1, 5.6);

      // Save PDF
      pdf.save(`Verification_Report_${certId}.pdf`);

    } catch (err) {
      console.error("Failed to generate report:", err);
      alert("Failed to generate the verification report.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={loading}
      className="w-full flex items-center justify-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/20 text-white rounded font-bold tracking-wide transition-colors border border-white/20 disabled:opacity-50"
    >
      {loading ? (
        <Loader2 className="w-5 h-5 animate-spin" />
      ) : (
        <FileDown className="w-5 h-5" />
      )}
      Download Verification Report
    </button>
  );
}
